### ISSUE TITLE
Unable to install binary on Python 3.11

### ISSUE THREAD

**Issue by victorhartman** [randy3k/rapi#22]
On windows 10 x64, pip version 22.3.1, using python 3.11, using command:

`py.exe -m pip install -U rchitect --only-binary :all:`
results in:
```
ERROR: Could not find a version that satisfies the requirement rchitect (from versions: none)
ERROR: No matching distribution found for rchitect
```

**Comment by randy3k** [comment]
rchitect 0.3.40 has just released, it contains wheels for python 3.11.
