### ISSUE TITLE
imp removed in python 3.12 and improper version comparison

### ISSUE THREAD

**Issue by theAeon** [randy3k/rapi#27]
Hi-I was attempting to compile this for python 3.12 and I think I stumbled into a bug in your vendored copy of reticulate that was likely present on 3.10 and 3.11 but did not become an issue until the removal of imp in python 3.12. It appears that the version comparison at the link below detects python 3.1x as less than python 3.4. This needs to be replaced with a comparison to the sys.version_info tuple if the modern importlib codepath is to be used on python 3.1x and for the library to function on python 3.12 _at all_.
https://github.com/randy3k/rchitect/blob/d2def76c6fc182dae79c87d9e8e415d63d062026/rchitect/reticulate/py_config.py#L6

Best,
Andrew

**Comment by randy3k** [comment]
Thank you for raising it. https://github.com/randy3k/rchitect/commit/d1bf82fbc98e887ed37b23a27f11c4cc87d603f0 should have fixed it. Will publish a release soon.
